name: Tests
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
jobs:
  test:
    runs-on: [self-hosted, macOS]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Testing App
        run: exec ./.github/scripts/test_app.sh arm
